// Generated by the protocol buffer compiler.  DO NOT EDIT!

package test;

public final class UserPBO {
  private UserPBO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage {
    // Use User.newBuilder() to construct.
    private User() {}
    
    private static final User defaultInstance = new User();
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.UserPBO.internal_static_test_User_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.UserPBO.internal_static_test_User_fieldAccessorTable;
    }
    
    // required uint32 id = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string name = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated string email = 3;
    private java.util.List<java.lang.String> email_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getEmailList() {
      return email_;
    }
    public int getEmailCount() { return email_.size(); }
    public java.lang.String getEmail(int index) {
      return email_.get(index);
    }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeUInt32(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      for (java.lang.String element : getEmailList()) {
        output.writeString(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (java.lang.String element : getEmailList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static test.UserPBO.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.UserPBO.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.UserPBO.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static test.UserPBO.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static test.UserPBO.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.UserPBO.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static test.UserPBO.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static test.UserPBO.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(test.UserPBO.User prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using test.UserPBO.User.newBuilder()
      private Builder() {}
      
      test.UserPBO.User result = new test.UserPBO.User();
      
      @Override
      protected test.UserPBO.User internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new test.UserPBO.User();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.UserPBO.User.getDescriptor();
      }
      
      public test.UserPBO.User getDefaultInstanceForType() {
        return test.UserPBO.User.getDefaultInstance();
      }
      
      public test.UserPBO.User build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private test.UserPBO.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public test.UserPBO.User buildPartial() {
        if (result.email_ != java.util.Collections.EMPTY_LIST) {
          result.email_ =
            java.util.Collections.unmodifiableList(result.email_);
        }
        test.UserPBO.User returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.UserPBO.User) {
          return mergeFrom((test.UserPBO.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(test.UserPBO.User other) {
        if (other == test.UserPBO.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.email_.isEmpty()) {
          if (result.email_.isEmpty()) {
            result.email_ = new java.util.ArrayList<java.lang.String>();
          }
          result.email_.addAll(other.email_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              addEmail(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // repeated string email = 3;
      public java.util.List<java.lang.String> getEmailList() {
        return java.util.Collections.unmodifiableList(result.email_);
      }
      public int getEmailCount() {
        return result.getEmailCount();
      }
      public java.lang.String getEmail(int index) {
        return result.getEmail(index);
      }
      public Builder setEmail(int index, java.lang.String value) {
        result.email_.set(index, value);
        return this;
      }
      public Builder addEmail(java.lang.String value) {
        if (result.email_.isEmpty()) {
          result.email_ = new java.util.ArrayList<java.lang.String>();
        }
        result.email_.add(value);
        return this;
      }
      public Builder addAllEmail(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.email_.isEmpty()) {
          result.email_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.email_);
        return this;
      }
      public Builder clearEmail() {
        result.email_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      test.UserPBO.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_User_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\023protobuf/user.proto\022\004test\"/\n\004User\022\n\n\002i" +
      "d\030\001 \002(\r\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \003(\tB\021\n\004" +
      "testB\007UserPBOH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_User_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", },
              test.UserPBO.User.class,
              test.UserPBO.User.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
